name: build

on: [push]

jobs:
    build-ubuntu-20-04:
        name: ubuntu-20.04
        runs-on: ubuntu-latest
        container:
            image: ubuntu:20.04
            env:
                TZ: America/New_York
                DEBIAN_FRONTEND: noninteractive
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: apt
                run: |
                    apt-get update
                    apt-get -y upgrade
                    apt install -y build-essential software-properties-common
                    add-apt-repository ppa:ubuntu-toolchain-r/test
                    apt-get install -y \
                        cmake \
                        git \
                        ninja-build \
                        g++-9 \
                        clang-9
            -   name: build-release-g++
                run: |
                    mkdir build-release-g++
                    cd build-release-g++
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=gcc-9 \
                        -DCMAKE_CXX_COMPILER=g++-9 \
                        ..
                    ninja
            -   name: build-release-clang
                run: |
                    mkdir build-release-clang
                    cd build-release-clang
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=clang-9 \
                        -DCMAKE_CXX_COMPILER=clang++-9 \
                        ..
                    ninja
            -   name: test-release-g++
                run: |
                    cd build-release-g++
                    ctest -v
            -   name: test-release-clang
                run: |
                    cd build-release-clang
                    ctest -v
    build-fedora-31:
        name: fedora-32
        runs-on: ubuntu-latest
        container:
            image: fedora:32
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: dnf
                run: |
                    sudo dnf install -y \
                        cmake \
                        git \
                        ninja-build \
                        gcc-c++-10.2.1 \
                        clang-10.0.0 \
                        lcov
            -   name: build-debug-g++
                run: |
                    mkdir build-debug-g++
                    cd build-debug-g++
                    cmake \
                        -GNinja \
                        -DTURBOHTTP_CODE_COVERAGE=ON \
                        -DCMAKE_BUILD_TYPE=Debug \
                        -DCMAKE_C_COMPILER=gcc \
                        -DCMAKE_CXX_COMPILER=g++ \
                        ..
                    ninja
            -   name: build-release-g++
                run: |
                    mkdir build-release-g++
                    cd build-release-g++
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=gcc \
                        -DCMAKE_CXX_COMPILER=g++ \
                        ..
                    ninja
            -   name: build-release-clang
                run: |
                    mkdir build-release-clang
                    cd build-release-clang
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=clang \
                        -DCMAKE_CXX_COMPILER=clang++ \
                        ..
                    ninja
            -   name: test-release-g++
                run: |
                    cd build-release-g++
                    ctest -v
            -   name: test-release-clang
                run: |
                    cd build-release-clang
                    ctest -v
            -   name: Build coverage info
                run: |
                    cd build-debug-g++
                    ctest -v
                    gcov -o ./test/CMakeFiles/libturbohttp_tests.dir/main.cpp.o ./test/libturbohttp_tests
                    lcov --include "*/inc/lift/*" --include "*/src/*" --exclude "test/*" -o libturbohttp_tests.info -c -d .
            -   name: Coveralls GitHub Action
                uses: coverallsapp/github-action@v1.0.1
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    path-to-lcov: build-debug-g++/libturbohttp_tests.info
